FROM golang:1.26.2-alpine

WORKDIR /app

RUN apk update && apk upgrade && \
    mkdir -p /.cache && chmod 777 /.cache

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml", "-build.args_bin", "--dashboard=true"]
