FROM golang:1.26.0-alpine3.23

WORKDIR /app

RUN mkdir -p /.cache && chmod 777 /.cache

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml", "-build.args_bin", "--dashboard=true"]
