schemaVersion: 2
dns:
    address: 0.0.0.0
    gateway: ""
    cacheEnabled: false
    cacheTTL: 360
    dnssec:
        enabled: false
        mode: "off"
    rateLimit:
        enabled: true
        maxQueries: 120
        windowSeconds: 10
        blockDurationSeconds: 30
    udpSize: 512
    tls:
        enabled: false
        cert: ""
        key: ""
    upstream:
        servers:
            - name: Preferred (Migrated)
              address: 8.8.8.8:53
              protocol: udp
              enabled: true
            - name: Fallback 1 (Migrated)
              address: 1.1.1.1:53
              protocol: udp
              enabled: true
    ports:
        udptcp: 53
        dot: 853
        doh: 443
    conditionalForwarders: []
    resolution:
        '*.wildcard.host': 10.10.0.2
        another.host: 192.168.1.50
        example.host: 192.168.0.2
dhcp:
    enabled: false
    address: 0.0.0.0
    interface: ""
    ipv4Enabled: true
    ipv6Enabled: false
    rangeStart: 192.168.0.100
    rangeEnd: 192.168.0.250
    rangeStartV6: ""
    rangeEndV6: ""
    leaseDuration: 86400
    router: 192.168.0.1
    dnsServers:
        - 0.0.0.0
    dnsServersV6: []
    domainSearch: lan
    ports:
        ipv4: 67
        ipv6: 547
api:
    port: 8080
    authentication: true
    jwtSecret: aAOij2bY_jYYsj3Hs7u8pEdsR2nkmg9-ZJ0yFJEO5Vw
    rateLimit:
        enabled: true
        maxTries: 5
        window: 5
logging:
    enabled: true
    level: 1
misc:
    inAppUpdate: false
    statisticsRetention: 7
    anonymizeIP: false
    dashboard: true
    scheduledBlacklistUpdates: true
remoteBackup:
    enabled: false
    provider: ""
    endpoint: ""
    bucket: ""
    region: ""
    accessKey: ""
    secretKey: ""
    username: ""
    password: ""
    schedule: manual
highAvailability:
    enabled: false
    mode: primary
    clusterId: ""
    priority: 0
    peers: []
    heartbeatUrl: ""
    proxy:
        enabled: false
        port: 0
    vip:
        enabled: false
        interface: ""
        address: ""
    replicaSyncInterval: 15m
    primaryBackupProvider: ""
    primaryBackupEndpoint: ""
    primaryBackupBucket: ""
    primaryBackupRegion: ""
    primaryBackupAccessKey: ""
    primaryBackupSecretKey: ""
    primaryBackupUsername: ""
    primaryBackupPassword: ""
