sonar.projectKey=goaway
sonar.projectName=GoAway
sonar.projectVersion=0.91.0

# Path to source directories
sonar.sources=backend,client/src
sonar.exclusions=**/*.test.go,client/src/**/*.spec.ts,client/src/**/*.test.tsx,client/dist/**,resources/**

# Go specific configuration
sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=test-report.out

# Frontend specific configuration
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info
sonar.typescript.tsconfigPath=client/tsconfig.json

# Quality Gates and Analysis
sonar.sourceEncoding=UTF-8
sonar.cpd.exclusions=**/*.test.go
